# Generated by Django 4.0.3 on 2022-08-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generatorius',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Kiekis')),
                ('category', models.IntegerField(verbose_name='Kategorija')),
                ('difficulty', models.CharField(max_length=10, verbose_name='Kategorija')),
            ],
            options={
                'verbose_name': 'Generatorius',
                'verbose_name_plural': 'Generatoriai',
            },
        ),
    ]
